### ISSUE TITLE
API: s3:PutPublicAccessBlock Access Denied

### ISSUE THREAD

**Issue by hfp** [buildkite/elastic-ci-stack-for-aws#1116] opened 2023-05-08 18:55 UTC
Launching a new stack fails for me with "API: s3:PutPublicAccessBlock Access Denied". This is the "first" red event when scrolling back in the event log of the failed stack creation. I had earlier versions of the stack successfully working in production. Setting up an older version of elastic-ci-stack-for-aws is meanwhile also no solution and fails (unexpectedly?) due to some changed behavior on AWS side, e.g., v5.17 fails (TODO to paste error from event log). Releases like v5.19 or v5.20 supposedly with the fix in place (to overcome the AWS change) however fail with aforementioned "API: s3:PutPublicAccessBlock Access Denied". Note: I have unblocked all S3-settings found under https://s3.console.aws.amazon.com/s3/settings called "Block Public Access settings for this account" - still no luck. ATM, I cannot create a Buildkite stack on AWS.

**Comment by hfp** [comment] 2023-05-09 08:12
Apparently, S3-buckets created when launching a new AWS stack are still blocked in my case even if https://s3.console.aws.amazon.com/s3/settings supposedly unblocks.

**Comment by hfp** [comment] 2023-05-09 11:21
I was able to launch the latest stack (v5.20). This was only possible by relying on an S3-bucket created upfront, i.e., `SecretsBucket` was specified.

**Comment by moskyb** [comment] 2023-05-17 03:58
hi there @hfp! i've just stood up a stack on my account, and didn't run into any problems, so i suspect that the issue here is that the IAM principal creating the cloudformation stack doesn't have the `s3:PutPublicAccessBlock` permission. would you be able to verify this? if this isn't the case, i can look into it a bit further.

**Comment by triarius** [comment] 2023-07-05 01:21
Hi @hfp we're closing this as we're not able to reproduce. If you have further questions, feel free to comment here or reach out to support@buildkite.com.

**Closed by triarius** 2023-07-05 01:21 UTC
