### ISSUE TITLE
Inconsistent authentication with ECR due to incorrectly formed config.json file. 

### ISSUE THREAD

**Issue by paulcollingwood2** [buildkite/elastic-ci-stack-for-aws#449] opened 2018-07-11 09:30 UTC
Over the last few days sometimes instances come up correctly authenticated against the ECR, and sometimes not. 

The elastic environment step looks like it correctly ran. However it cannot be pulled from:

```
ERROR: Get https://xxxxx.dkr.ecr.eu-west-1.amazonaws.com/xx/xx/xx/manifests/latest: no basic auth credentials
🚨 Error: The local post-checkout hook exited with an error: Error running `/bin/bash -c /tmp/buildkite-agent-bootstrap-hook-runner-602498344`: exit status 1
--
  | # Skipping artifact upload, no artifact upload path set
  | 🚨 Error: Error running `/bin/bash -c /tmp/buildkite-agent-bootstrap-hook-runner-602498344`: exit status 1
```

This is has been an issue on and off for a while, but it seems to be affecting everything today. I have noticed that adding the login-step for the docker-compose plug helps, but this has worked as-is for months. 

In this case I'm pulling in the post checkout hook, but it happens anywhere in the pipeline when attempting to pull an image from ECR.

Steps to reproduce: 

1. Run a build where the ECS Repo is under a different account to the buildkite agent where the agent account has permission to pull images and AWS_ECR_LOGIN_REGISTRY_IDS contains the account id where the repo is located.
2. When the build fails SSH to the agent and switch to the buildkite-agent user then `cat .docker/config.json`

```{
        "auths": {
                "9xxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com": {
                        "auth": "<Removed>"
                }
                // Missing the account id where the repo is located
        }
}```

If I duplicate the first account id and it's auth and change it to the other account id then the docker pull is successful.

On agents where there is no issue both account ids are present in this file.

**Comment by lox** [comment] 2018-07-11 10:00
Sorry you've run into this @paulcollingwood2! We've seen this very occasionally in other customer installations and have never identified a root cause. In the builds that are failing, can you see the ECR authentication plugin authenticating? I'm wondering if it's some sort of docker authentication race condition, or ordering problem.

**Comment by paulcollingwood2** [comment] 2018-07-11 10:50
Hi,
This is the sequence on a failed run, and it does look as if we have authed with ECR. 
```
Running global environment hook | 0s
-- | --
  |   | Setting up elastic stack environment (v2.3.3) | 0s
  |   | Downloading secrets from  xxx | 5s
  |   | Preparing build directory | 5s
  |   | Running global pre-command hook | 0s
  |   | Authenticating with AWS ECR | 1s
  |   | Running local pre-command hook | 3s
  |   | Running command | 0s
  | $ /bin/bash -c /var/lib/buildkite-agent/builds/buildkite-v3-agent-i-xx-1/xx/xx/buildkite-script-xx-xx-4157-xx-xx
  | $ docker pull xx.dkr.ecr.eu-west-1.amazonaws.com/xx/xx
  | Error response from daemon: Get https://xx.dkr.ecr.eu-west-1.amazonaws.com/v2/xx/xx/manifests/base-image: no basic auth credentials
```
And from a different, failed run a logs:
```
Running global environment hook
# Executing "/tmp/buildkite-agent-bootstrap-hook-runner-292593940"
$ /bin/bash -c /tmp/buildkite-agent-bootstrap-hook-runner-292593940
    :llama: Setting up elastic stack environment (v2.3.3)
export DOCKER_VERSION=17.12.0-ce
export BUILDKITE_STACK_NAME=buildkite-v3-agent
export BUILDKITE_STACK_VERSION=v2.3.3
export BUILDKITE_AGENTS_PER_INSTANCE=1
export BUILDKITE_SECRETS_BUCKET=buildkite-xx-xx
export AWS_DEFAULT_REGION=eu-west-1
export AWS_REGION=eu-west-1
export PLUGINS_ENABLED="secrets ecr docker-login"
export BUILDKITE_ECR_POLICY=poweruser
export BUILDKITE_USERNS_REMAP={DOCKER_USERNS_REMAP}
Checking docker processes
2800 /usr/bin/dockerd -s overlay2 --debug
2808 docker-containerd --config /var/run/docker/containerd/containerd.toml
Configuring built-in plugins
Secrets plugin enabled
ECR plugin enabled
Docker-login plugin enabled
    Downloading secrets from :amazon-s3: xx-xx-xx
Checking exporter/private_ssh_key
Checking exporter/id_rsa_github
Checking private_ssh_key
Found private_ssh_key, downloading
Downloaded 3242 bytes of ssh key
Starting an ephemeral ssh-agent
Agent pid 25651
Loading ssh-key into ssh-agent (pid 25651)
Identity added: (stdin) ((stdin))
Checking id_rsa_github
Downloading env file from env
Evaluating 46 bytes of env
Fixing permissions for 'buildkite-v3-agent-i-xxx-1/xx/xx'...
 
# Applying working directory change: /
# Changing working directory to "/"
# AWS_ECR_LOGIN_REGISTRY_IDS changed
# BUILDKITE_STACK_VERSION changed
# BUILDKITE_AGENTS_PER_INSTANCE changed
# DOCKER_VERSION changed
# BUILDKITE_USERNS_REMAP changed
# BUILDKITE_ECR_POLICY changed
# BUILDKITE_SECRETS_BUCKET changed
# SSH_AGENT_PID changed
# AWS_REGION changed
# ECR_PLUGIN_ENABLED changed
# SSH_AUTH_SOCK changed
# PLUGINS_ENABLED changed
# BUILDKITE_PLUGIN_S3_SECRETS_BUCKET changed
# DOCKER_LOGIN_PLUGIN_ENABLED changed
# AWS_DEFAULT_REGION changed
# BUILDKITE_STACK_NAME changed
# SECRETS_PLUGIN_ENABLED changed
```

We're experiencing the problem on most pipelines now.

**Comment by paulcollingwood2** [comment] 2018-07-11 11:38
Using the ecr login plugin and specifying the account_id and login:true  works, but it's never been required before.

**Comment by philipCrunchboards** [comment] 2019-03-05 10:07
Recently this issue has been affecting us more frequently.

**Comment by lox** [comment] 2019-03-05 21:12
It's possible this is related to a race condition between parallel builds on the same host. Given there is a single docker config, it's entirely possible that parallel login / logouts are causing problems.

**Comment by philipCrunchboards** [comment] 2019-03-11 12:17
This has been fixed on our end.
We were using the ECR plugin rather than setting the environment variables according to the [documentation](https://github.com/buildkite/elastic-ci-stack-for-aws#docker-registry-support).

**Comment by keithduncan** [comment] 2021-07-02 06:50
I can’t see any reports of this since [per-job docker config](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/756) was released in version 5, hopefully that has fixed this issue for everyone.

If anyone is still experiencing issues with Docker login please let us know and we can investigate 🙇‍♂️

**Closed by keithduncan** 2021-07-02 06:50 UTC
