### ISSUE TITLE
sudo not working for user "buildkite-agent" without password

### ISSUE THREAD

**Issue by pliljenberg** [buildkite/elastic-ci-stack-for-aws#330] opened 2017-08-22 12:35 UTC
When running as `buildkite-agent` sudo requires a password. This makes installation of packages from environment scripts almost impossibe. I know I could build a custom AMI and use but sometimes it's nice to use the standard template configuration and install during build.
Adding:

    buildkite-agent ALL=(ALL) NOPASSWD:ALL

to [sudoers.conf](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/sudoers.conf) probably fixes that?

**Comment by lox** [comment] 2017-08-25 03:14
Hi @pliljenberg! That's by design, we've tried to restrict the permissions that the `buildkite-agent` user has intentionally. That said, you still have access to the docker socket, which is basically root access. 

I'd suggest customizing `sudoers.conf` as you suggested in the `BootstrapScriptUrl` parameter of the stack. Alternately, you can use docker containers to run things as root, which is what we do.

**Comment by lox** [comment] 2017-09-02 03:02
I'm going to close this, let me know if I can help further!

**Closed by lox** 2017-09-02 03:02 UTC

**Comment by celsodantas** [comment] 2019-04-06 09:08
Alternative is also to add: `NOPASSWD:ALL` to `BuildkiteAdditionalSudoPermissions` of the stack, or be more specific about what permissions you need to have available.

**Comment by gjthompson1** [comment] 2019-04-10 02:43
You might also have to update your template to get `BuildkiteAdditionalSudoPermissions` for anyone else coming here. https://github.com/buildkite/elastic-ci-stack-for-aws/releases

@celsodantas  Thank You!
