### ISSUE TITLE
Environment variable BUILDKITE_SECRETS_BUCKET doesn't override the default secret bucket name

### ISSUE THREAD

**Issue by wangdanny** [buildkite/elastic-ci-stack-for-aws#159] opened 2016-10-31 04:42 UTC
I tried to set BUILDKITE_SECRETS_BUCKET with a new bucket name "buildkite-pipelines-secrets" but apparently the old bucket name (SecretsBucket property set in cloudformation) is still used by the pipeline to look for a private key. This can be verified in the pipeline log and environment variables.

1. click the failed pipeline
2. select the Log tab. The log shows
 "Downloading secrets...
No SSH keys found in s3://{old bucket name}"
 
3. go to the "Environment" tab, find that
BUILDKITE_SECRETS_BUCKET="buildkite-pipelines-secrets"

**Comment by gugahoi** [comment] 2016-11-02 01:03
You might need to refresh your agents. Updating cloudformation doesn't kill the original ones as they are still healthy so you will need to replace them with new ones.

**Comment by gugahoi** [comment] 2016-11-02 01:20
It looks like the description for this section `Configuration Environment Variables` is misleading. If `BUILDKITE_SECRETS_BUCKET` is defined through cloudformation then it cannot be overwritten on a pipeline as the [cfn-env file is sourced](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/hooks/environment#L29) before downloading the secrets.

**Comment by lox** [comment] 2016-11-08 20:14
The issue is that permission to access the bucket needs to be assigned by the stack. Why not just update the stack itself? 

I agree @gugahoi, it should be more clearly documented.

**Comment by lox** [comment] 2017-01-11 04:11
This is now under `Instance Configuration`, I'm going to close this for now unless it's still an issue.

**Closed by lox** 2017-01-11 04:11 UTC
