### ISSUE TITLE
Intermittent docker error "could not find an available predefined network"

### ISSUE THREAD

**Issue by zain** [buildkite/elastic-ci-stack-for-aws#148] opened 2016-09-20 01:16 UTC
I see these on builds occasionally:

```
$ docker-compose -f docker-compose.yml -p buildkite9c0e505a3f5844e4bde33ee36c928627 run node pug-lint app/assets/javascripts
Creating network "buildkite9c0e505a3f5844e4bde33ee36c928627_default" with the default driver
ERROR: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
```

Here's the Dockerfile I'm using:

```
FROM node:4.5.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install
RUN npm install -g eslint babel-eslint pug-lint

COPY . /usr/src/app
```

and the pipeline.yml:

```
steps:
  - name: ":docker:"
    plugins:
      docker-compose:
        build: node

  - wait

  - name: ":eslint:"
    command: "eslint --cache app/assets/javascripts spec/javascripts"
    plugins:
      docker-compose:
        run: node

  - name: ":dog:"
    command: "pug-lint app/assets/javascripts"
    plugins:
      docker-compose:
        run: node
```

**Comment by lox** [comment] 2016-09-20 01:49
I'd suggest you change those docker registry credentials now ;)

**Comment by lox** [comment] 2016-09-20 01:50
Perhaps related to this docker issue? https://github.com/docker/docker/issues/23971

**Comment by keithpitt** [comment] 2016-09-20 01:50
@lox already done :)

**Comment by lox** [comment] 2016-09-20 01:51
On reading the above issue a bit more, looks like there is a limit on the number of networks created, I wonder if we are not correctly cleaning up after builds with `docker-compose down`

**Comment by zain** [comment] 2016-09-21 23:58
Running this fixes the issue, but it's not really a solution because I can't just constantly be running this. `docker network ls | awk '{print $1}' | xargs docker network rm`

**Comment by lox** [comment] 2016-09-22 23:31
Which version of the stack are you seeing this in @zain? I don't have much experience with the docker-compose plugin, as it's not in the stable release. It does look to me like the networks aren't being cleaned up after each command.

**Comment by lox** [comment] 2016-09-22 23:31
Perhaps @sj26 might know.

**Comment by sj26** [comment] 2016-09-23 07:14
There is docker-compose support in the stable version using environment variables. :-)

We are running `docker-compose down` at the end of builds which should also remove any created networks:

https://github.com/buildkite/agent/blob/2-2-stable/templates/bootstrap.sh#L498-L499

We also run it in plugin (used by the beta agent):

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/run.sh#L43

But perhaps it might be worth looking at previous builds to see if this command is throwing errors? It's done in cleanup in a collapsed build log section so I don't think its exit status changes the build status and it might not be super visible.

We also suffer from this problem! Although I had absolutely no idea what those errors meant. docker-compose should probably be throwing more descriptive errors when this happens.

**Comment by zain** [comment] 2016-10-04 00:54
Our CI server goes for less than a day before all builds start erroring out with this message. I'm using the unstable version of the buildkite-agent (v3.0-beta.9). Here's the pipeline.yml that is currently causing this error: 

```yml
steps:
  - name: ":docker:"
    plugins:
      docker-compose:
        build: web
    agents:
      queue: big
  - wait
  - name: ":rspec:"
    command: .buildkite/scripts/run-rspec.sh
    plugins:
      docker-compose:
        run: web
    parallelism: 16
    agents:
      queue: big
```

and the `run-rspec.sh` script:
```bash
#!/bin/bash

set -eo pipefail

.buildkite/scripts/wait-for-it.sh -t 600 db:5432
bundle exec rake db:create knapsack_pro:rspec SPEC_OPTS="--tag ~js"
```

This is pretty much a blocker for us to be able to use buildkite, so hoping you guys have some more insight here.

**Comment by zain** [comment] 2016-10-04 00:59
This might shed some light. This is our docker-compose.yml:

```yml
version: '2'

services:
  db:
    image: mdillon/postgis:9.4
  elasticsearch:
    image: elasticsearch:2.3
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - elasticsearch
```

And the output of `$ docker ps` is a huge list of `mdillon/postgis:9.4` and `elasticsearch:2.3` containers.

**Comment by zain** [comment] 2016-10-04 01:07
...and to fix the problem this time, I ran `docker kill $(docker ps -q)` and `docker network ls | awk '{print $1}' | xargs docker network rm`.

**Comment by sj26** [comment] 2016-10-07 04:51
@zain are you seeing a header section "Cleaning up Docker containers" in your build logs? Any chance you could post the insides?

**Comment by zain** [comment] 2016-10-11 20:47
@sj26 yep, here's the section.

```
Killing buildkite279eba5af07a4454b4514ecbd8b71b41_elasticsearch_1 ... done
Killing buildkite279eba5af07a4454b4514ecbd8b71b41_elasticsearch_1 ...
$ docker-compose -f docker-compose.yml -p buildkite279eba5af07a4454b4514ecbd8b71b41 rm --force --all
WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`
Removing buildkite279eba5af07a4454b4514ecbd8b71b41_web_run_1 ... done
Removing buildkite279eba5af07a4454b4514ecbd8b71b41_web_run_1 ...
Removing buildkite279eba5af07a4454b4514ecbd8b71b41_db_1 ... done
$ docker-compose -f docker-compose.yml -p buildkite279eba5af07a4454b4514ecbd8b71b41 down
Removing network buildkite279eba5af07a4454b4514ecbd8b71b41_default
```

**Comment by lox** [comment] 2016-10-11 21:40
That's strange, it looks like it's correctly running the docker-compose down bit. Next time you get the error, are you able to check out the output of `docker network ls` and see if there are a lot of `buildkitexxxxxxx` networks, or something else in there?

**Comment by zain** [comment] 2016-11-02 00:49
Sorry -- we're not running buildkite anymore so I can't check. The docker issue was closed recently though, and there's a suggestion to use `--subnet`: https://github.com/docker/docker/issues/23971#issuecomment-255210570

**Comment by lox** [comment] 2016-11-08 20:18
I'm going to close this, that issue looks like it's basically just saying "use docker-compose down". @sj26 my only parting thought is perhaps we aren't calling docker-compose down on failed builds?

**Comment by zain** [comment] 2016-11-08 20:25
Pretty sure this is a premature close of an issue you guys want to fix. It's not a failed build thing because I'm able to reproduce it w/ zero red builds. Because of this issue, it's impossible to use docker and buildkite together with multiple agents on one machine for anything more complicated than hello world.

**Comment by lox** [comment] 2016-11-09 02:15
Given you are the only person experiencing it though and you aren't using it any more, it makes fixing it tough :) 

Might it have been that you had only a very small subset of docker subnets available? Did you use the built in VPC, or were you using your own?

**Comment by zain** [comment] 2016-11-09 02:23
I'm using the default configuration entirely -- whatever CloudFormation spins up.

**Comment by lox** [comment] 2016-11-09 02:24
What region?

**Comment by zain** [comment] 2016-11-09 02:28
us-east-1.

**Comment by lox** [comment] 2016-11-09 02:36
And you are definitely on the latest version of the stack?

It would be very interesting to add this as a `.buildkite/hooks/post-command` so that we can see whether there genuinely too many networks or if there is a key value store corruption: 

```
docker network ls
```

**Comment by toolmantim** [comment] 2016-11-10 01:02
Could you paste some of your CloudFormation configuration in here, such as the number of agents per instance, min-max since, instance type, etc. And then we could spin up a test stack with a similar Dockerfile, configure a job with parallelism set to 16, and trigger a bunch of builds?

**Comment by lox** [comment] 2016-11-10 03:44
Hey @zain, on re-reading this, I could have been a lot more helpful. I think you are entirely likely correct and it's an issue with high concurrency agents. 

We will put our heads together and test somethings. Might you be in a position to test it if we come up with a fix?

**Comment by lox** [comment] 2017-01-11 04:13
I've spent some time trying to reproduce this with 100+ agents in varying configurations. Have certainly found lots of bugs, but not this specific one. Would be keen to hear from anyone else having this problem.

**Comment by deppy** [comment] 2017-03-08 12:27
To give a bit of feedback on my experience with this exact error...

I've come across it both in buildkite and in my local development environments.  It is indeed related to too many networks.  We had 1-2 custom buildkite jobs which were using our own scripts for startup/shutdown and so we were leaving behind a few networks.  As soon as we fixed those custom jobs, these errors went away 100%. 

The limit seems to be ~30  (at least on my local machine) + bridge/host networks as can be seen in:
```
$ for count in `seq 1 35` ; do echo -n "$count: " ; docker network create test$count ; done
1: 02b8f09541f28f1a0d5487d649de07a32a01524d20632f967ce2a928369db497
2: ca4a53df632735e7703b5e33c5ffc84d3873bfe883199509d7ef65bd59c52a98
3: 607219dc2ddc3c69d606137d3a0054b6ad56c7d6b4b3c82c514bc4bf91668d84
4: 679d79c5aee9a75f595130f7a8c017df88874475c84a3b486a54c26a9c3f1dbf
5: 96cbac056a95c8ee3009cd5daaecf634f6f3c93d8e1bc8c2e4c0010ecae617dc
6: 0c83931ae3557e52f23d93026b545653b6feeac9b3537148bcc29249ed040887
7: c15651836c7580e266c3b2903f1d786a1ccdb7a2cbc9f2327a90d331835d9920
8: 65947d9cf7f81393c4f235d080211d9954cefeac402fd217be4ce142de110dc3
9: 66314a00fbcdb2517f7a86fa0fe3b1cba381a4e8dbcd1315d34f18f585cd4a18
10: 70ae74d7c00efe3cf29ad3ce2813b9df81e7c7064262c3fa41362047abacb297
11: a677989da5731d31b660e8831f4f5682db160742ae850d7f2e5ce7e77b65d932
12: 274c41ea932bd40eb92572b48912c1522570eb21a45e5090af2381471fad5e9a
13: fbb1f756b1a92bd8e673d12db595897170baf08a898036498d93830eda3a4a31
14: 0a67a72a2bc4460c1c9db16f5d27efe21c714b1a0f8fc2a1c26fd0e9207553e0
15: 0049f09c3de8ba48d435dc7fab71adb5a39cd8d9cd6d5ee7bb7bd3f6e6b72691
16: 557aea91dda8f5988c9e3661f5377ac861c9f5e7862bb4e5bd02aa120885bcaa
17: 04e09bea616d09a0f082797d8783924d759d36c29cd411c48bbe5ed1aa242dc0
18: 8a151874a9002f1f9add48056f5974d2a5867bf16219a8b4a4b4ce4c3b679ff6
19: 61b5cd5632c04e3951a2d22e000db67b36e25ea8683d9d6f74cd111f9888927c
20: 6cea8e771f3699ae232d3f04ed40078e0d8c0e2196715df3e1ff645dc35ac433
21: 0046e52998c0d2ef213cb400bb0a44899c779782848b49e91f8719f0aacccc48
22: d58ec78a1731b482f90b3c467c220c2b40cbe8c9d068ed98686ee32f39fde1f2
23: 7542c46e1e4f99e68278188a7a50aaceb764dc65301393b93189349f9462fbf4
24: 6889b21c4e8a5776652fe54812b00dd36a48445bdcddc15a5e1284944a5b4c11
25: 04bdf9e51e2d373aa98fe11ac3cb57722a0fcc5a1a17322f8b8d28218d2ad3e7
26: 63e6c1637da62f5d4fbc34f824b5e978bb24dbccb78b1d57cca1078b7bf4f3d6
27: b65828bca18d06e1428985360a617d37294e5427b806bdce248c86f99cbe9a76
28: d950c8933a8ca48ed33773cfe08c901a04030f2f77e9c919fcda7cac05e47e46
29: 677cc64a291f934a7fd637162c46f2955d07b5bd9e508f185ad312026b7b2808
30: b4c25ea1c6eadeff3031092e10e0cdefc76481b0a411f38aa34e44e7c7390ffc
31: Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
32: Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
33: Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
34: Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
35: Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
```

The fix for this is not related to buildkite at all, but if you wanted to fix this on the buildkite side you could periodically check for all networks, see if any jobs are currently running, and if not cleanup those orphaned networks.

**Comment by lox** [comment] 2017-04-14 22:40
Interesting @deppy, I hadn't thought that it might be networks created within a build. We are actually already cleaning up networks by virtue of calling `docker system prune` every day via cron:

https://docs.docker.com/engine/reference/commandline/system_prune/

I suppose the frequency might be the issue? We should possibly consider detecting this condition and running `docker network prune` in response.

I'm going to close this one for now. If you see this issue again @zain or @deppy on the latest stack (post 2.0), let's re-evaluate.

**Closed by lox** 2017-04-14 22:40 UTC

**Comment by DanielHeath** [comment] 2020-10-06 21:50
I'm finding it easy to reproduce - if you use a single large runner with multiple agents, and your builds use `docker-compose`, you can quickly exhaust the available networks.

If we could specify a larger CIDR for docker networks, that would help.

Related: https://github.com/buildkite/elastic-ci-stack-for-aws/issues/512

**Comment by yob** [comment] 2020-10-06 21:55
Thanks for the extra details @DanielHeath.

> if you use a single large runner with multiple agents

Out of interest, which instance type are you using and how many agents per instance?

> your builds use docker-compose

Are you using the docker compose plugin, or docker-compose directly?

**Comment by DanielHeath** [comment] 2020-10-06 21:56
c5.9xlarge with 12 agents. Using docker-compose directly, but I had the same issue with the plugin.
